#!/bin/bash
# shellcheck disable=SC1091
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
source "/usr/libexec/dwpar2cron/const.sh" || exit 2

echo "Clearing par2cron logfiles..."
echo "Clearing par2cron logfiles..." | logger -t "par2cron-plugin"

rm -f "$P2C_LOG_FILE"
rm -f "$P2C_JSON_FILE"
