#!/bin/bash
# shellcheck disable=SC1091
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
umask 000

source "/boot/config/plugins/dwpar2cron/dwpar2cron.cfg" || exit 2
source "/usr/libexec/dwpar2cron/const.sh" || exit 2

if [ -f "$P2C_PID_FILE" ]; then
    if kill -0 "$(cat "$P2C_PID_FILE")" 2>/dev/null; then
        echo "par2cron is already running; exiting" | logger -s -t "par2cron-plugin"
        exit 1
    else
        rm -f "$P2C_PID_FILE"
    fi
fi
echo $$ > "$P2C_PID_FILE"
trap 'rm -f "$P2C_PID_FILE"' EXIT

OPNOTIFY="${1:-}"

log_json() {
    local level="${1:-INFO}"
    local msg="$2"
    local op="${3:-}"
    local timestamp=$(date +"%Y-%m-%dT%H:%M:%S%:z")

    printf '{"time":"%s","level":"%s","msg":"%s","op":"%s"}\n' \
        "$timestamp" "$level" "$msg" "$op" | tee >("$P2C_SVLOGD" "$P2C_JSON_DIR") | "$P2C_SVLOGD" "$P2C_LOG_DIR"
}

EXTRA_ARGS=()
if [ "$PPROF" == "enable" ]; then
    EXTRA_ARGS+=(--pprof "/tmp/par2cron-pprof-info-$(date +%Y%m%d-%H%M%S).pb.gz")
fi

log_json "INFO" "Scanning filesystem for jobs..." "info"

IFS='|' read -ra OPSCOPE_ARRAY <<< "${OPSCOPE:-/mnt/user}"

echo "info: started" | logger -t "par2cron-plugin"

wait
sleep 3
sync

/usr/bin/par2cron info \
    "${EXTRA_ARGS[@]}" \
    --cache "$P2C_CACHE_DIR" \
    -c /boot/config/plugins/dwpar2cron/config.yaml \
    --json \
    "${OPSCOPE_ARRAY[@]}" \
    </dev/null \
    > /usr/local/emhttp/plugins/dwpar2cron/info.json \
    2> >(tee >("$P2C_SVLOGD" "$P2C_JSON_DIR") | "$P2C_SVLOGD" "$P2C_LOG_DIR")
RET=$?

wait
sleep 3
sync

case "$RET" in
0)
    log_json "INFO" "Operation finished (return code: $RET - success)" "info"
    ;;
1)
    log_json "ERROR" "Operation finished (return code: $RET - partial failure)" "info"
    ;;
2)
    log_json "ERROR" "Operation finished (return code: $RET - bad invocation)" "info"
    ;;
5)
    log_json "ERROR" "Operation finished (return code: $RET - unclassified error)" "info"
    ;;
143)
    log_json "ERROR" "Operation finished (return code: $RET - interrupted)" "info"
    ;;
*)
    log_json "ERROR" "Operation finished (return code: $RET - unexpected return code)" "info"
    ;;
esac

NOTIFY_BIN="/usr/local/emhttp/plugins/dynamix/scripts/notify"
HOST=$(echo "$HOSTNAME" | awk '{print toupper($0)}')
EVENT="par2cron-UI"
SUBJECT="[${HOST}] par2cron-UI:"

case "$RET" in
0)
    echo "info: finished (return code: ${RET} - success)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Notice ${SUBJECT} Info: Success" -d "Operation has finished with success." -i "normal"
    ;;
1)
    echo "info: finished (return code: ${RET} - partial failure)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Partial Failure" -d "Not all jobs could be processed." -i "alert"
    ;;
2)
    echo "info: finished (return code: ${RET} - bad invocation)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Bad Invocation" -d "A bad invocation error was returned." -i "alert"
    ;;
3)
    echo "info: finished (return code: ${RET} - repairable corruption)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Repairable Corruption" -d "Operation has detected repairable corruption." -i "alert"
    ;;
4)
    echo "info: finished (return code: ${RET} - unrepairable corruption)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Unrepairable Corruption" -d "Operation has detected unrepairable corruption." -i "alert"
    ;;
5)
    echo "info: finished (return code: ${RET} - unclassified error)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Unclassified Error" -d "An unclassified error was returned." -i "alert"
    ;;
143)
    echo "info: finished (return code: ${RET} - interrupted)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Interrupted" -d "An interruption exit code was returned." -i "alert"
    ;;
*)
    echo "info: finished (return code: ${RET} - unexpected return code)" | logger -t "par2cron-plugin"
    [ "$OPNOTIFY" == "1" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Info: Unexpected Code" -d "An unexpected exit code was returned." -i "alert"
    ;;
esac
