#!/bin/bash
# shellcheck disable=SC1091
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
source "/usr/libexec/dwpar2cron/const.sh" || exit 2

BOOT="/boot/config/plugins/dwpar2cron"
DOCROOT="/usr/local/emhttp/plugins/dwpar2cron"

echo "Resetting par2cron configuration..."
echo "Resetting par2cron configuration..." | logger -t "par2cron-plugin"

rm -f "$P2C_LOG_FILE"
rm -f "$P2C_JSON_FILE"
rm -f /usr/local/emhttp/plugins/dwpar2cron/info.json
rm -f /tmp/par2cron-pprof-*.pb.gz

rm -rf /mnt/user/system/par2cron
rm -rf /dev/shm/par2cron
rm -rf /tmp/par2cron

cp -f $DOCROOT/default.cfg $BOOT/dwpar2cron.cfg
cp -f $DOCROOT/defaults/default.yaml $BOOT/config.yaml

if [ -x /usr/local/emhttp/plugins/dwpar2cron/scripts/write_config ]; then
    /usr/local/emhttp/plugins/dwpar2cron/scripts/write_config
fi

echo "par2cron is now reset to defaults, reboot or reinstall plugin in case of any problems."
