#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
umask 000

source "/boot/config/plugins/dwpar2cron/dwpar2cron.cfg"

echo "Starting par2cron (Verify Mode)..."
echo "Starting par2cron (Verify Mode)..." | logger -t "par2cron-plugin"

rm -f /var/log/dwpar2cron.json
rm -f /var/log/dwpar2cron.log
rm -f /tmp/par2cron-pprof-*.pb.gz

if [ "$PPROF" == "enable" ]; then
    PPROFARG="--pprof /tmp/par2cron-pprof-verify-$(date +%Y%m%d-%H%M%S).pb.gz"
fi

IFS='|' read -ra OPSCOPE_ARRAY <<< "${OPSCOPE:-/mnt/user}"

nohup /usr/bin/par2cron verify \
    $PPROFARG \
    -c /boot/config/plugins/dwpar2cron/config.yaml \
    --json \
    "${OPSCOPE_ARRAY[@]}" \
    </dev/null \
    >> /var/log/dwpar2cron.log \
    2> >(tee -a /var/log/dwpar2cron.json >> /var/log/dwpar2cron.log 2>&1) &

sleep 1
