#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
umask 000

echo "Starting par2cron (Info Mode)..."
echo "Starting par2cron (Info Mode)..." | logger -t "par2cron-plugin"

rm -f /var/log/dwpar2cron.json
rm -f /var/log/dwpar2cron.log
rm -f /usr/local/emhttp/plugins/dwpar2cron/info.json
rm -f /tmp/par2cron-pprof-*.pb.gz

nohup /usr/local/emhttp/plugins/dwpar2cron/scripts/info </dev/null >/dev/null 2>&1 &

sleep 2
