#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
umask 000

echo "Starting par2cron (Create Mode)..."
echo "Starting par2cron (Create Mode)..." | logger -t "par2cron-plugin"

nohup /usr/bin/par2cron create \
    -c /boot/config/plugins/dwpar2cron/config.yaml \
    --json \
    /mnt/user \
    </dev/null \
    > >(tee -a /tmp/dwpar2cron.log) \
    2> >(tee -a /tmp/dwpar2cron.json >> /tmp/dwpar2cron.log) &

sleep 1
