#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
umask 000

echo
echo "Please wait, this process may take a while"
echo "DO NOT CLOSE THE WINDOW UNTIL COMPLETION IS REPORTED"
echo

echo "Scanning filesystem for jobs..."

/usr/bin/par2cron info \
    -c /boot/config/plugins/dwpar2cron/config.yaml \
    --json \
    /mnt/user \
    2>&1 \
    > /usr/local/emhttp/plugins/dwpar2cron/info.json
RET=$?

case "$RET" in
0)
    echo "Operation finished (return code: $RET - success)"
    ;;
1)
    echo "Operation finished (return code: $RET - partial failure)"
    ;;
2)
    echo "Operation finished (return code: $RET - bad invocation)"
    ;;
5)
    echo "Operation finished (return code: $RET - unclassified error)"
    ;;
*)
    echo "Operation finished (return code: $RET - unexpected return code)"
    ;;
esac

echo
echo "It is now safe to close the window using the button"
if [ "$RET" -eq 0 ]; then
    echo "You can find the information report after the page refreshes"
    echo "It is located at the bottom of the page, scroll all the way down"
else
    echo "Please retry later and/or report the failure to the developers"
fi
echo

