#!/bin/bash
# shellcheck disable=SC1091
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
umask 000

source "/usr/libexec/dwpar2cron/const.sh" || exit 2

if [ -f "$P2C_PID_FILE" ]; then
    if kill -0 "$(cat "$P2C_PID_FILE")" 2>/dev/null; then
        echo "par2cron is already running; exiting" | logger -s -t "par2cron-plugin"
        exit 1
    else
        rm -f "$P2C_PID_FILE"
    fi
fi

OPCMD="${1:-}"
OPNOTIFY="${2:-}"

if [ -z "$OPCMD" ]; then
    echo "Usage: $0 <command> [notify]" | logger -s -t "par2cron-plugin"
    exit 1
fi

echo "Starting par2cron (${OPCMD^} Mode)..."
echo "Starting par2cron (${OPCMD^} Mode)..." | logger -t "par2cron-plugin"

rm -f "$P2C_LOG_FILE"
rm -f "$P2C_JSON_FILE"
rm -f /tmp/par2cron-pprof-*.pb.gz

if [ "$OPCMD" == "info" ]; then
    rm -f /usr/local/emhttp/plugins/dwpar2cron/info.json
    nohup /usr/local/emhttp/plugins/dwpar2cron/scripts/cmd_info "$OPNOTIFY" </dev/null >/dev/null 2>&1 &
else
    nohup /usr/local/emhttp/plugins/dwpar2cron/scripts/cmd_other "$OPCMD" "$OPNOTIFY" </dev/null >/dev/null 2>&1 &
fi

sleep 3
